model_type: "api"      
api_provider: "openai" 
api_key: "sk-xxx..."   
api_model_name: "gpt-3.5-turbo"

judge_model_type: "api"
judge_api_model_name: "gpt-3.5-turbo"

local_model_name: "decapoda-research/llama-7b-hf"
