model_type: "api"      # "api" 或 "local"
api_provider: "openai" # 如果是 openai
api_key: "sk-xxx..."   # 你的API key
api_model_name: "gpt-3.5-turbo"

judge_model_type: "api"
judge_api_model_name: "gpt-3.5-turbo"

local_model_name: "decapoda-research/llama-7b-hf"
